package com.yaojian.sphtest.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yaojian.sphtest.greendao.entity.SphInfo;

import com.yaojian.sphtest.greendao.dao.SphInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sphInfoDaoConfig;

    private final SphInfoDao sphInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sphInfoDaoConfig = daoConfigMap.get(SphInfoDao.class).clone();
        sphInfoDaoConfig.initIdentityScope(type);

        sphInfoDao = new SphInfoDao(sphInfoDaoConfig, this);

        registerDao(SphInfo.class, sphInfoDao);
    }
    
    public void clear() {
        sphInfoDaoConfig.clearIdentityScope();
    }

    public SphInfoDao getSphInfoDao() {
        return sphInfoDao;
    }

}
